spring.application.name=com-app

# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Add prepareThreshold=0 to disable server-prepared statements
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&preparedStatementCacheQueries=0

spring.datasource.username=postgres.vmiqoagknvqthoegnwjq
spring.datasource.password=Mahjoub!@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# HikariCP configuration for Supabase pooler
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

server.port=9090

jwt.secret=cinema-secret-key-must-be-at-least-32-chars!!
jwt.expiration=86400000

# Main Admin Configuration
app.main-admin.email=mainadmin@cinema.com
app.main-admin.password=admin123
app.main-admin.name=Main Admin

# Supabase Storage
supabase.url=https://vmiqoagknvqthoegnwjq.supabase.co
supabase.service-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtaXFvYWdrbnZxdGhvZWdud2pxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODA5ODExNCwiZXhwIjoyMDkzNjc0MTE0fQ.nqFD3Gw37JF6nmhZMji7S5MQsNVc7PCpcDMVioBK8-8
supabase.bucket=movies