spring.application.name=com-app

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.vmiqoagknvqthoegnwjq
spring.datasource.password=Mahjoub!@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.port=9090

jwt.secret=cinema-secret-key-must-be-at-least-32-chars!!
jwt.expiration=86400000
